# Generated code do not commit.
file(TO_CMAKE_PATH "/usr/local/flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/user/TraeCN/fluttermusic" PROJECT_DIR)

set(FLUTTER_VERSION "1.5.1+12" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 5 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 1 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 12 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/usr/local/flutter"
  "PROJECT_DIR=/home/user/TraeCN/fluttermusic"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzguMTA=,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049YzZmNjdkZWRlMw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049Y2FmY2RhNTcyMQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC45"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=true"
  "PACKAGE_CONFIG=/home/user/TraeCN/fluttermusic/.dart_tool/package_config.json"
  "FLUTTER_TARGET=lib/main.dart"
)
